force-app/main/default/objects/Installment__c/fields/Amounts__c.field-meta.xml
<CustomField>
    <fullName>Amounts__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Installment__c/fields/of_Payment__c.field-meta.xml
<CustomField>
    <fullName>of_Payment__c</fullName>
    <label>% of Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Installment__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Installment__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Installments</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installment__c/fields/Property_Unit__c.field-meta.xml
<CustomField>
    <fullName>Property_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Unit</label>
    <referenceTo>Property_Unit__c</referenceTo>
    <relationshipLabel>Installments</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Installment__c/fields/Sales_Booking__c.field-meta.xml
<CustomField>
    <fullName>Sales_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Booking</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Installments</relationshipLabel>
    <relationshipName>Installments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Unit_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Property_Unit__c.Inventory_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>$Source.Project_Name__c</field>
            <operation>equals</operation>
            <valueField>Property_Unit__c.Property__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Property_Unit__c</referenceTo>
    <relationshipLabel>Sales Bookings</relationshipLabel>
    <relationshipName>Sales_Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Online Payment</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>Internal Transfer</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Sales Bookings</relationshipLabel>
    <relationshipName>Sales_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Sales Bookings</relationshipLabel>
    <relationshipName>Sales_Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <label>Down Payment</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/Installment_Days_Range__c.field-meta.xml
<CustomField>
    <fullName>Installment_Days_Range__c</fullName>
    <label>Installment Day&apos;s Range</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/fields/Number_of_Installment__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Installment__c</fullName>
    <label>Number of Installment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Unit__c/Property_Unit__c.object-meta.xml
<CustomObject>
    <label>Property Unit</label>
    <nameField>
        <label>Property Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Unit__c/fields/Original_Price__c.field-meta.xml
<CustomField>
    <fullName>Original_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property_Unit__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Units</relationshipLabel>
    <relationshipName>Property_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SalesBookingInstallmentHandlerTest.cls
@IsTest
public class SalesBookingInstallmentHandlerTest {
 @IsTest
     static void testGenerateInstallments() {
        
        Payment_Plan__c plan = new Payment_Plan__c(
            Name = 'Standard Payment Plan – 0% Discount',
            Number_of_Installment__c = 30,
            Discount_Percent__c = 0,
            Down_Payment__c = 10,
            Installment_Days_Range__c = '1 Month'
        );
        insert plan;
        
         Property__c prop = new Property__c();
         prop.Name = 'Test 0123';
         insert prop;
         
        Property_Unit__c unit = new Property_Unit__c(
            Name = 'Test Unit',
            Original_Price__c = 100000,
            Property__c = prop.id
        );
        insert unit;
        
        Opportunity opp = new Opportunity(
            Name = 'Test Sales Booking',
            StageName = 'Prospecting',
            CloseDate = Date.today(),
            Payment_Plan__c = plan.Id,
            Customer_Unit_Name__c = unit.Id,
            Mode_of_Payment__c = 'cash',
            Project_Name__c = prop.Id
        );
        insert opp;
        
        Test.startTest();
        
        SalesBookingInstallmentHandler.generateInstallments(
            new List<Opportunity>{opp}
        );
        
        Test.stopTest();
        
        List<Installment__c> instList = [
            SELECT Id, Name, Date__c, of_Payment__c, Amounts__c, Sales_Booking__c
            FROM Installment__c
            WHERE Sales_Booking__c = :opp.Id
        ];
        
        System.assertEquals(30, instList.size(), '30 Installments should be created');
        
        Installment__c firstInst = instList[0];
        System.assertEquals('Down Payment - Installment 1', firstInst.Name);
        
        Installment__c lastInst = instList[29];
        System.assertEquals('Installment 30 (Handover)', lastInst.Name);
        
        System.assertNotEquals(null, firstInst.Date__c);
        System.assertNotEquals(null, firstInst.Amounts__c);
    }
    
    @IsTest
    static void testNoInstallmentsWhenPaymentPlanMissing() {
        
         Property__c prop1 = new Property__c();
         prop1.Name = 'Test 0123';
         insert prop1;
        
        Property_Unit__c unit = new Property_Unit__c(
            Name = 'Unit Without Plan',
            Original_Price__c = 50000,
            Property__c = prop1.id
        );
        insert unit;
        
       Opportunity opp = new Opportunity(
    Name = 'Opportunity No Plan',
    StageName = 'Prospecting',
    CloseDate = Date.today(),
    Customer_Unit_Name__c = unit.Id,
    Mode_of_Payment__c = 'cash',
    Project_Name__c = prop1.Id
);
        insert opp;
        
        Test.startTest();
        SalesBookingInstallmentHandler.generateInstallments(
            new List<Opportunity>{opp}
        );
        Test.stopTest();
        
        List<Installment__c> instList = [
            SELECT Id FROM Installment__c
            WHERE Sales_Booking__c = :opp.Id
        ];
        
        System.assertEquals(0, instList.size(), 'No installments should be created');
    }
}