force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/Sales_Offer__c.field-meta.xml
<CustomField>
    <fullName>Sales_Offer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Offer</label>
    <referenceTo>Sales_Offer__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Unit__c/Property_Unit__c.object-meta.xml
<CustomObject>
    <label>Property Unit</label>
    <nameField>
        <label>Property Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Unit__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Units</relationshipLabel>
    <relationshipName>Property_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/Sales_Offer__c.object-meta.xml
<CustomObject>
    <label>Sales Offer</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Offer #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Offer__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard Payment Plan – 0% Discount</fullName>
            </value>
            <value>
                <fullName>30% Down Payment – 4% Discount</fullName>
            </value>
            <value>
                <fullName>50% Down Payment – 8% Discount</fullName>
            </value>
            <value>
                <fullName>100% Down Payment (No ROI) – 20% Discount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Sales Offers</relationshipLabel>
    <relationshipName>Sales_Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/fields/Property_Unit__c.field-meta.xml
<CustomField>
    <fullName>Property_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Property_Unit__c.Inventory_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Property_Unit__c</referenceTo>
    <relationshipLabel>Sales Offers</relationshipLabel>
    <relationshipName>Sales_Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesOfferProjectBasedPDFControllerTest.cls
@IsTest
public class SalesOfferProjectBasedPDFControllerTest {

    @TestSetup
    static void setupTestData() {
        // Create Projects
        Property__c miorahProject = new Property__c(Name = 'Miorah Hills');
        insert miorahProject;

        Property__c zoyaProject = new Property__c(Name = 'Nuve by Zoya');
        insert zoyaProject;

        // Create Property Units
        Property_Unit__c property1 = new Property_Unit__c(
            Name = 'Unit A',
            Property__c = miorahProject.Id
        );
        insert property1;

        Property_Unit__c property2 = new Property_Unit__c(
            Name = 'Unit B',
            Property__c = zoyaProject.Id
        );
        insert property2;

        // Create Sales Offers (Miorah)
        Sales_Offer__c miorahOffer1 = new Sales_Offer__c(
            Project__c = miorahProject.Id,
            Property_Unit__c = property1.Id,  
            Payment_Plan__c = 'Standard Payment Plan – 0% Discount'
        );

        Sales_Offer__c miorahOffer2 = new Sales_Offer__c(
            Project__c = miorahProject.Id,
            Property_Unit__c = property1.Id,
            Payment_Plan__c = '30% Down Payment – 4% Discount'
        );

        // Create Sales Offers (Nuve by Zoya)
        Sales_Offer__c zoyaOffer1 = new Sales_Offer__c(
            Project__c = zoyaProject.Id,
            Property_Unit__c = property2.Id,
            Payment_Plan__c = '50% Down Payment – 8% Discount'
        );

        insert new List<Sales_Offer__c>{miorahOffer1, miorahOffer2, zoyaOffer1};

        // Store inserted records in static variables for test methods
        Test.setFixedSearchResults(new List<Id>{miorahOffer1.Id, miorahOffer2.Id, zoyaOffer1.Id});
    }

    @IsTest
    static void testMiorahPaymentPlan() {
        Sales_Offer__c offer = [SELECT Id, Project__c, Property_Unit__c, Payment_Plan__c FROM Sales_Offer__c WHERE Payment_Plan__c = 'Standard Payment Plan – 0% Discount' LIMIT 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(offer);

        Test.startTest();
        SalesOfferProjectBasedPDFController controller = new SalesOfferProjectBasedPDFController(sc);
        Test.stopTest();

        
    }

    @IsTest
    static void testZoyaPaymentPlan() {
        Sales_Offer__c offer = [SELECT Id, Project__c, Property_Unit__c, Payment_Plan__c FROM Sales_Offer__c WHERE Payment_Plan__c = '50% Down Payment – 8% Discount' LIMIT 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(offer);

        Test.startTest();
        SalesOfferProjectBasedPDFController controller = new SalesOfferProjectBasedPDFController(sc);
        Test.stopTest();

      
    }
    
    @IsTest
static void testSetPdfFileName() {
    // Create a dummy page reference for testing
    PageReference pageRef = new PageReference('/apex/dummy'); // any URL works
    Test.setCurrentPage(pageRef);

    // Query an existing offer (from your TestSetup)
    Sales_Offer__c offer = [SELECT Id, Name, Project__c, Property_Unit__c, Payment_Plan__c 
                             FROM Sales_Offer__c 
                             LIMIT 1];

    ApexPages.StandardController sc = new ApexPages.StandardController(offer);

    Test.startTest();
    SalesOfferProjectBasedPDFController controller = new SalesOfferProjectBasedPDFController(sc);

    // Call the method
    controller.setPdfFileName();
    Test.stopTest();

    // Assert that the header was set correctly
    String contentDisposition = ApexPages.currentPage().getHeaders().get('Content-Disposition');
   // System.assert(contentDisposition.contains('SalesOffer_' + offer.Name + '.pdf'),
                //  'PDF filename header should be set correctly');
}


}