force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/Sales_Offer__c.field-meta.xml
<CustomField>
    <fullName>Sales_Offer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Offer</label>
    <referenceTo>Sales_Offer__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Unit__c/Property_Unit__c.object-meta.xml
<CustomObject>
    <label>Property Unit</label>
    <nameField>
        <label>Property Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Unit__c/fields/Original_Price__c.field-meta.xml
<CustomField>
    <fullName>Original_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/Sales_Offer__c.object-meta.xml
<CustomObject>
    <label>Sales Offer</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Offer #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Offer__c/fields/Net_Price__c.field-meta.xml
<CustomField>
    <fullName>Net_Price__c</fullName>
    <formula>Original_Price__c * (1 - Offer_Promotion__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/fields/Offer_Promotion__c.field-meta.xml
<CustomField>
    <fullName>Offer_Promotion__c</fullName>
    <formula>CASE(
    Payment_Plan__c,
    &quot;Standard Payment Plan – 0% Discount&quot;, 0,
    &quot;30% Down Payment – 4% Discount&quot;, 0.04,
    &quot;50% Down Payment – 8% Discount&quot;, 0.08,
    &quot;100% Down Payment (No ROI) – 20% Discount&quot;, 0.20,
    &quot;100% Down Payment (With ROI) – 0% Discount&quot;, 0,
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offer/Promotion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/fields/Original_Price__c.field-meta.xml
<CustomField>
    <fullName>Original_Price__c</fullName>
    <formula>Property_Unit__r.Original_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Original Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard Payment Plan – 0% Discount</fullName>
            </value>
            <value>
                <fullName>30% Down Payment – 4% Discount</fullName>
            </value>
            <value>
                <fullName>50% Down Payment – 8% Discount</fullName>
            </value>
            <value>
                <fullName>100% Down Payment (No ROI) – 20% Discount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Sales Offers</relationshipLabel>
    <relationshipName>Sales_Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/fields/Property_Unit__c.field-meta.xml
<CustomField>
    <fullName>Property_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Property_Unit__c.Inventory_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Property_Unit__c</referenceTo>
    <relationshipLabel>Sales Offers</relationshipLabel>
    <relationshipName>Sales_Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(Property_Unit__r.Unit_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/miorahSalesOfferController.cls
public with sharing class miorahSalesOfferController {

    public Sales_Offer__c offer { get; set; }
    public List<InstallmentRow> installmentList { get; set; }
    public Integer totalRows { get; set; }
    public Date dealDate { get; set; }

    // ===== Payment Summary =====
    public Decimal downPaymentPercent { get; set; }
    public Decimal downPaymentAmount { get; set; }
    public Decimal dldPercent { get; set; }
    public Decimal dldAmount { get; set; }
    public Decimal adminFee { get; set; }
    public Decimal totalPaymentAmount { get; set; }
    
     public String projectName { get; set; }
     public String propertyName { get; set; } 
     public String recordOwnerName { get; set; }

    public miorahSalesOfferController() {

        Id recordId = ApexPages.currentPage().getParameters().get('id');
        if (recordId == null) return;

        offer = [
    SELECT Id, Name, Payment_Plan__c,
           Project__c,
           Project__r.Name,
           Property_Unit__c,
           Property_Unit__r.Name, 
           Type__c, Original_Price__c,
           Offer_Promotion__c, Net_Price__c,  Owner.Name
    FROM Sales_Offer__c
    WHERE Id = :recordId
    LIMIT 1
];


        dealDate = Date.today();

        Decimal baseAmount =
            offer.Net_Price__c != null
            ? offer.Net_Price__c
            : offer.Original_Price__c;

        adminFee = 3500;
        dldPercent = 4;
        dldAmount = (baseAmount * dldPercent / 100).setScale(2);
        
        
        projectName = offer.Project__r.Name;
        propertyName = offer.Property_Unit__r.Name;
         recordOwnerName  = offer.Owner.Name;
        
        
        installmentList = new List<InstallmentRow>();

        // =========================
        // PICKLIST → RULE MAPPING
        // =========================
        Map<Integer, Decimal> specialPercents = new Map<Integer, Decimal>();

        if (offer.Payment_Plan__c == 'Standard Payment Plan – 0% Discount') {
            totalRows = 58;
            downPaymentPercent = 20;
            specialPercents.put(1, 20);
        }
        else if (offer.Payment_Plan__c == '30% Down Payment – 4% Discount') {
            totalRows = 58;
            downPaymentPercent = 30;
            specialPercents.put(1, 30);
        }
        else if (offer.Payment_Plan__c == '50% Down Payment – 8% Discount') {
            totalRows = 58;
            downPaymentPercent = 50;
            specialPercents.put(1, 50);
        }
        else if (offer.Payment_Plan__c == '100% Down Payment (No ROI) – 20% Discount') {
            totalRows = 1;
            downPaymentPercent = 100;
        }
        else {
            totalRows = 58;
            downPaymentPercent = 20;
            specialPercents.put(1, 20);
        }

        // Common special installments
        if (totalRows > 1) {
            specialPercents.put(21, 10);       // 21st installment
            specialPercents.put(totalRows, 6); // last installment
        }

        downPaymentAmount =
            (baseAmount * downPaymentPercent / 100).setScale(2);

        totalPaymentAmount =
            downPaymentAmount + dldAmount + adminFee;

        // =========================
        // INSTALLMENT GENERATION
        // =========================
        Date startDate = dealDate.addMonths(1);

        for (Integer i = 1; i <= totalRows; i++) {

            Decimal percent;

            if (totalRows == 1) {
                percent = 100;
            }
            else if (specialPercents.containsKey(i)) {
                percent = specialPercents.get(i);
            }
            else {
                percent = 1;
            }

            Decimal amount =
                (baseAmount * percent / 100).setScale(2);

            installmentList.add(
                new InstallmentRow(
                    i,
                    startDate.addMonths(i - 1),
                    percent,
                    amount
                )
            );
        }
    }

    // ===== Wrapper =====
    public class InstallmentRow {
        public String label { get; set; }
        public Date milestoneDate { get; set; }
        public Decimal percent { get; set; }
        public Decimal amount { get; set; }

        public InstallmentRow(
            Integer index,
            Date d,
            Decimal p,
            Decimal a
        ) {
            label = 'Installment ' + index;
            milestoneDate = d;
            percent = p;
            amount = a;
        }
    }
}