force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/Sales_Offer__c.field-meta.xml
<CustomField>
    <fullName>Sales_Offer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Offer</label>
    <referenceTo>Sales_Offer__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>Payment_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Property_Unit__c.field-meta.xml
<CustomField>
    <fullName>Property_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Unit</label>
    <referenceTo>Property_Unit__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Unit__c/Property_Unit__c.object-meta.xml
<CustomObject>
    <label>Property Unit</label>
    <nameField>
        <label>Property Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Unit__c/fields/Original_Price__c.field-meta.xml
<CustomField>
    <fullName>Original_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property_Unit__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Property Units</relationshipLabel>
    <relationshipName>Property_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property_Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1BED</fullName>
            </value>
            <value>
                <fullName>1BED-L</fullName>
            </value>
            <value>
                <fullName>2BED</fullName>
            </value>
            <value>
                <fullName>Exe Studio</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/Sales_Offer__c.object-meta.xml
<CustomObject>
    <label>Sales Offer</label>
    <nameField>
        <displayFormat>SO-{000000}</displayFormat>
        <label>Sales Offer #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Offer__c/fields/Original_Price__c.field-meta.xml
<CustomField>
    <fullName>Original_Price__c</fullName>
    <formula>Property_Unit__r.Original_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Original Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard Payment Plan – 0% Discount</fullName>
            </value>
            <value>
                <fullName>30% Down Payment – 4% Discount</fullName>
            </value>
            <value>
                <fullName>50% Down Payment – 8% Discount</fullName>
            </value>
            <value>
                <fullName>100% Down Payment (No ROI) – 20% Discount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Sales Offers</relationshipLabel>
    <relationshipName>Sales_Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Offer__c/fields/Property_Unit__c.field-meta.xml
<CustomField>
    <fullName>Property_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Unit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Property_Unit__c.Inventory_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Property_Unit__c</referenceTo>
    <relationshipLabel>Sales Offers</relationshipLabel>
    <relationshipName>Sales_Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesOfferPaymentPlanControllerTest.cls
@IsTest 
public class SalesOfferPaymentPlanControllerTest {
    
    @TestSetup
    static void setupTestData() {
        // Create and activate a standard pricebook for tests
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        update standardPricebook; // This activates the standard pricebook in test context
    }
    
    @IsTest 
    public static void createSalesOfferWithAllData() {
        // Get the standard pricebook ID using Test.getStandardPricebookId()
        // This works because we activated it in setupTestData()
        Id stdPricebookId = Test.getStandardPricebookId();
        
        // Create a custom pricebook for testing
        Pricebook2 customPricebook = new Pricebook2(
            Name = 'Test Pricebook ' + DateTime.now().getTime(),
            IsActive = true
        );
        insert customPricebook;
        
        // Create product
        Product2 prod = new Product2(
            Name = 'Test Product',
            IsActive = true
        );
        insert prod;
        
        // Create pricebook entry for standard pricebook
        PricebookEntry stdPbe = new PricebookEntry(
            Pricebook2Id = stdPricebookId,
            Product2Id = prod.Id,
            UnitPrice = 1000,
            IsActive = true,
            UseStandardPrice = false
        );
        insert stdPbe;
        
        // Create pricebook entry for custom pricebook
        PricebookEntry customPbe = new PricebookEntry(
            Pricebook2Id = customPricebook.Id,
            Product2Id = prod.Id,
            UnitPrice = 1000,
            IsActive = true
        );
        insert customPbe;
        
        // Create property
        Property__c prop = new Property__c(Name = 'Test Property');
        insert prop;
        
        // Create property unit
        Property_Unit__c unit = new Property_Unit__c(
            Name = '0101',
            Property__c = prop.Id,
            Original_Price__c = 1000000,
            Unit_Type__c = '1BED'
        );
        insert unit;
        
        // Create sales offer
        Sales_Offer__c offer = new Sales_Offer__c(
            Payment_Plan__c = '30% Down Payment – 4% Discount',
            Project__c = prop.Id,
            Property_Unit__c = unit.Id
        );
        insert offer;
        
                
        Test.startTest();
        
        // Set the current page parameters for controller
        PageReference pageRef = new PageReference('/apex/Sales_Offer_PaymentPlan');
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', offer.Id);
        
        // Initialize controller
        ApexPages.StandardController sc = new ApexPages.StandardController(offer);
        SalesOfferPaymentPlanController controller = new SalesOfferPaymentPlanController(sc);
        Decimal downPayment = controller.getDownPaymentAmount();
        Decimal remaining = controller.getRemainingAmount();
         Integer remainingCount = controller.getRemainingInstallmentCount();
         Decimal discountDecimal = controller.getDiscountPercentDecimal();
        String discountStr = controller.getPaymentPlanDiscountPercent();
        Decimal totalPayment = controller.getTotalPaymentAmount();
        controller.setPdfFileName();
        Sales_Offer__c offer100 = new Sales_Offer__c(
            Payment_Plan__c = '100% Down Payment (No ROI) – 20% Discount',
            Project__c = prop.Id,
            Property_Unit__c = unit.Id
        );
        insert offer100;
        ApexPages.currentPage().getParameters().put('id', offer100.Id);
        SalesOfferPaymentPlanController controller100 = new SalesOfferPaymentPlanController(new ApexPages.StandardController(offer100));
        Test.stopTest();
    }
}